---
# tasks file for roles/omero-user

# Forcibly reset OMERO root password
- name: omero user | get root password update command
  become: yes
  become_user: "{{ omero_user_system }}"
  command: >
    {{ omero_user_bin_omero }} db password
    --user-id 0
    {{ omero_user_reset_root_password | quote }}
  register: rootpwdupdate

# WARNING: this will always run
- name: omero user | force reset omero password
  command: >
    psql
    -h {{ omero_user_dbhost }}
    -U {{ omero_user_dbuser }}
    -d {{ omero_user_dbname }}
    -w -c
    {{ rootpwdupdate.stdout | quote }}
  environment:
    PGPASSWORD: "{{ omero_user_dbpassword }}"
