---
# defaults file for roles/postgresql

# Version of postgres (see vars)
postgresql_version: "9.4"

# Whether to install and setup PostgreSQL server
postgresql_install_server: True

# List of dictionaries containing user and databases information
postgresql_users_databases: []

# Network interfaces to listen on
postgresql_server_listen: localhost

# Whether to enable the default local authentication methods
postgresql_server_auth_local: True

# List of dictionaries of client authorisation lines
postgresql_server_auth: []

# Recursively reset the owner/group of the postgres datadir?
postgresql_server_chown_datadir: False
