---
# defaults file for omero-server

# If True and server is already installed then upgrade to the version in
# omero_release, otherwise don't upgrade an existing server.
omero_upgrade: False

# If true create the postgres database if it doesn't already exist
omero_db_create: True

# If all the OMERO configuration is handled using ansible it should be
# possible to delete the entire server and re-install if the current
# installation appears to be corrupt (the data dir will not be touched)
# EXPERIMENTAL, may break your system
omero_reinstall_on_error: False

# OMERO system user
omero_system_user: omero

# OMERO system user ID (If not defined one is chosen automatically)
#omero_system_uid:

omero_basedir: /home/omero
#omero_serverdir: "{{ omero_basedir }}/server"
omero_serverdir: "{{ omero_basedir }}"
omero_server_symlink: OMERO.server
# WARNING: This will currently always attempt to update the server since the registry check is broken
omero_release: latest

# If non-empty dump the OMERO database to this directory before upgrading
omero_database_backupdir: "{{ omero_basedir }}/backups"

# OMERO database connection parameters
omero_dbhost: localhost
omero_dbuser: omero
omero_dbname: omero
omero_dbpassword: omero

# OMERO root password
omero_rootpassword: omero

# OMERO data directory
omero_datadir: /OMERO

# Create the OMERO data directory, set to False if storage is externally managed
omero_datadir_create: True

# Recursively set the owner on the OMERO data directory, use if the directory
# has been copied with an incorrect owner
omero_datadir_chown: False

# Path of the omego virtualenv
omero_omego_venv: "{{ omero_basedir }}/omego"

# Control verbosity of omego
omero_omego_verbosity: "-qq"

# Additional omego aguments passed to upgrade or install
omero_omego_additional_args: ""

# Dictionary of additional OMERO configuration options
omero_server_config: {}

# Optional path to an additional template-file to be passed to
# `omero load ...` before starting the server
omero_prestart_file:

# Setup OMERO.web
omero_web_install: True

# Configure SELinux
# EXPERIMENTAL
omero_selinux_setup: False

# Setup systemd services
# EXPERIMENTAL, may break your system
omero_systemd_setup: False

# Restart policy for systemd services
# EXPERIMENTAL, may break your system
# Quoted to prevent autoconversion to bool
omero_systemd_restart: "no"
