---
# Initial configuration of IDR nodes
# Note you should reboot after changing the network configuration, and
# manually verify that the configuration is correct

- hosts: idr
  roles:
  - role: openmicroscopy.upgrade-distpackages
  - role: server-swap
  - role: network
  #- role: system-monitor-agent

  post_tasks:
  - debug:
      msg: "You may need to reboot your system"
