---

# Force Docker to use the MTU set by the main IPV4 interface.
# This may be necessary on virtualised hosts, see comment in `docker/defaults/main.yml`.
docker_use_ipv4_nic_mtu: True

# path to snoopy keys like "/path/to/snoopy_keys"
snoopy_dir_path: ""

# devspace source
devspace_git_repo: "https://github.com/openmicroscopy/devspace.git"
# devspace branch
devspace_git_repo_version: "0.3.4"

# devspace user
devspace_user: omero

# devspace user id
devspace_user_id: "1001"
devspace_compose: "v1"

# path where devspace will be installed
devspace_home: /home/{{ devspace_user }}/devspace

# openstack IP e.g. 10.0.50.100
devspace_openstack_ip: "{{ ansible_host }}"

# rename to:
devspace_omero_branch: develop

# jenkins credentials:
devspace_jenkins_nginx_username: devspace
devspace_jenkins_nginx_password:

devspace_handler_tasks: "devspace-runtime.yml"

devspace_force_restart: true
