---
# defaults file for roles/openstack-idr-instance
# This contains a lot of the logic for setting the host and security
# groups based on the purpose of the VM, and is specific to the IDR
# playbooks

# Required vars:
#idr_vm_name
#idr_vm_image
#idr_vm_flavour

idr_vm_networks:
- net-name: "{{ idr_environment }}"

idr_vm_keyname: idr-deployment-key

idr_vm_assign_floating_ip: False

# idr_environment: All VMs will be put into this group
idr_environment: idr

# Number of VMs to create
idr_vm_count: 1

# Booleans indicating the purpose of this server (multiple may be True)
idr_vm_database: False
idr_vm_omero: False
idr_vm_proxy: False
idr_vm_dockermanager: False
idr_vm_dockerworker: False
idr_vm_bastion: False
idr_vm_management: False

# Default groups depend on the purpose of this server
idr_vm_groups: >
  {{
    (idr_vm_database | ternary(idr_vm_default_groups_database, [])) +
    (idr_vm_omero | ternary(idr_vm_default_groups_omero, [])) +
    (idr_vm_proxy | ternary(idr_vm_default_groups_proxy, [])) +
    (idr_vm_dockermanager | ternary(idr_vm_default_groups_dockermanager, [])) +
    (idr_vm_dockerworker | ternary(idr_vm_default_groups_dockerworker, [])) +
    (idr_vm_bastion | ternary(idr_vm_default_groups_bastion, [])) +
    (idr_vm_management | ternary(idr_vm_default_groups_management, []))
  }}

idr_vm_extra_groups: []

# Default security groups depend on the purpose of this server
idr_vm_security_groups: >
  {{
    ['default'] +
    (idr_vm_omero | ternary(['idr-omero-external'], [])) +
    (idr_vm_proxy | ternary(['idr-web-external'], [])) +
    (idr_vm_bastion | ternary(['idr-bastion-external'], [])) +
    (idr_vm_management | ternary(['idr-web-external'], []))
  }}

# Additional SSH metadata
idr_vm_ssh_metadata: "{{ idr_vm_bastion | ternary([('is_ssh_proxy_host', 'true')], []) }}"

idr_vm_default_groups_database:
- database-hosts
- "{{ idr_environment }}-database-hosts"
- "{{ idr_environment }}-hosts"

idr_vm_default_groups_omero:
- omero-hosts
- "{{ idr_environment }}-omero-hosts"
- "{{ idr_environment }}-hosts"

idr_vm_default_groups_proxy:
- proxy-hosts
- "{{ idr_environment }}-proxy-hosts"
- "{{ idr_environment }}-hosts"

idr_vm_default_groups_bastion:
- bastion-hosts
- "{{ idr_environment }}-bastion-hosts"
- "{{ idr_environment }}-hosts"

idr_vm_default_groups_dockermanager:
- dockermanager-hosts
- "{{ idr_environment }}-dockermanager-hosts"
- "{{ idr_environment }}-docker-hosts"
- "{{ idr_environment }}-hosts"
- "{{ idr_environment }}-data-hosts"

idr_vm_default_groups_dockerworker:
- dockerworker-hosts
- "{{ idr_environment }}-dockerworker-hosts"
- "{{ idr_environment }}-docker-hosts"
- "{{ idr_environment }}-hosts"

# Management nodes are special since they may cross multiple environments
idr_vm_default_groups_management:
- management-hosts
# TODO: Should they also be in an idr_environment group?
#- "{{ idr_environment }}-management-hosts"
