---
# tasks file for roles/omero-build

- name: system packages | install build tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ant
    - ant-contrib
    - doxygen
    - git
    - graphviz
    - make
    - maven

- name: system packages | install build libraries
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - boost-devel
    - libjpeg-turbo-devel
    - libpng-devel
    - libtiff-devel
    - xerces-c-devel
    - zlib-devel

- name: system packages | install python tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-devel
    - python-pip
    - python-virtualenv

- name: system packages | define epel packages
  set_fact: 
    omero_build_epel_packages="['hdf5-devel', 'GraphicsMagick']"

- name: system packages | install epel packages, server not spacewalk/satellite managed
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: epel
  with_items: "{{ omero_build_epel_packages }}"
  when: not spacewalk 

- name: system packages | install epel packages, server spacewalk/satellite managed
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ omero_build_epel_packages }}"
  when: spacewalk

# Ansible doesn't always detect when a downloaded file has been extracted,
# so use `creates` in `unarchive`

- name: cmake | download and extract
  become: yes
  unarchive:
    copy: no
    creates: /opt/cmake-3.3.2-Linux-x86_64/bin/cmake
    dest: /opt/
    src: http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz

- name: cmake | symlink
  become: yes
  file:
    force: yes
    path: /opt/cmake
    src: cmake-3.3.2-Linux-x86_64
    state: link

- name: cmake | set the global path to include cmake bin
  become: yes
  template:
    src: cmake-path.sh.j2
    dest: "/etc/profile.d/cmake-path.sh"
    # If the file exists, and is different to our version,
    # overwrite the dest with our version.
    force: yes
    mode: 0644

- name: exe4j packages | install
  become: yes
  yum:
    name: http://download-aws.ej-technologies.com/exe4j/exe4j_linux_5_0_1.rpm
    state: present

- name: exe4j packages | install license
  become: yes
  command: exe4jc -L="{{ exe4j_license_key }}"
  when: exe4j_license_key is defined

- name: findbugs | download and extract
  become: yes
  unarchive:
    copy: no
    creates: /opt/findbugs-3.0.0/bin/findbugs
    dest: /opt/
    src: http://prdownloads.sourceforge.net/findbugs/findbugs-3.0.0.tar.gz?download

- name: findbugs | symlink
  become: yes
  file:
    force: yes
    path: /opt/findbugs
    
    src: findbugs-3.0.0
    state: link

- name: ninja | create parent dir
  become: yes
  file:
    path: /opt/ninja-1.6.0
    state: directory

- name: ninja | download and extract
  become: yes
  unarchive:
    copy: no
    # Ansible doesn't detect when this already exists, so use creates:
    creates: /opt/ninja-1.6.0/ninja
    dest: /opt/ninja-1.6.0/
    src: https://github.com/martine/ninja/releases/download/v1.6.0/ninja-linux.zip

- name: ninja | symlink
  become: yes
  file:
    force: yes
    path: /opt/ninja
    src: ninja-1.6.0
    state: link
