---
# Playbook for creating OpenStack IDR VMs

# WARNING: Do not use set_facts in this role, since it'll create a hostvar
# on the host running the openstack client and not the VM created.
# This means multiple invocations of this role (for multiple VMs) will fail
# to work as expected since the hostvar is persistent across tasks.
# See defaults/main.yml for most of the logic.

- name: idr vm | create VM
  os_server:
    # Only add `-N` suffix for item>1
    name: "{{ idr_vm_name }}{{ (item | int > 1) | ternary('-' + item, '') }}"
    state: present
    image: "{{ idr_vm_image }}"
    key_name: "{{ idr_vm_keyname }}"
    flavor: "{{ idr_vm_flavour }}"
    nics: "{{ idr_vm_networks }}"
    auto_ip: "{{ idr_vm_assign_floating_ip }}"
    meta:
      hostname: "{{ idr_vm_name }}"
      groups: "{{ (idr_vm_groups + idr_vm_extra_groups) | join(',') }}"
    security_groups: "{{ idr_vm_security_groups | join(',') }}"
  register: vm
  with_sequence: "count={{ idr_vm_count }}"
