---

- name: virtualenv | install python tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-virtualenv
    
- name: virtualenv | scc
  become: yes
  become_user: "{{ jenkinsuser }}"
  pip:
    virtualenv: /home/{{ jenkinsuser }}/virtualenv
    name: scc Sphinx==1.2.3 genshi virtualenv epydoc yaclifw omego pytest docker-py PyYAML
