# Self-contained Ansible playbook for setting up the IDR NFS/samba shares
# The default is to use NFS, if you are using samba you must install the
# dependencies (cifs-utils) yourself.

- hosts: "{{ idr_environment | default('idr') }}-uod-nfs"

  vars:
    idr_mountpoint: /uod/idr
    # If you want to use samba instead of NFS change this to True, and
    # create a credentials file for samba:
    # https://www.samba.org/samba/docs/man/manpages-3/mount.cifs.8.html
    use_samba: False
    samba_credentials_file: /root/idr-samba.auth

  tasks:

  - name: Install NFS mount utility
    become: yes
    yum:
      name: nfs-utils
      state: present
    when: not use_samba

  # Do not create mountpoint using file, the mount module will create it
  # automatically. This avoids problems where the module tries to change
  # permissions on an existing directory

  - name: Mount NFS share
    become: yes
    mount:
      fstype: nfs4
      name: "{{ idr_mountpoint }}"
      opts: rsize=8192,wsize=8192,timeo=14,intr,ro
      src: idr-data.openmicroscopy.org:/idr
      state: mounted
    when: not use_samba

  - name: Mount samba share
    become: yes
    mount:
      fstype: cifs
      name: "{{ idr_mountpoint }}"
      opts: "credentials={{ samba_credentials_file }},ro"
      src: //idr-data.openmicroscopy.org/idr
      state: mounted
    when: use_samba
