# Example playbook for resetting the public user password on the IDR
# This is useful for giving people API access to a clone of the IDR
# without revealing the production public password
#
# Only run this if you are deploying a non production copy of the IDR for testing


- hosts: >
    {{ idr_environment | default('idr') }}-database-hosts
    {{ idr_environment | default('idr') }}-a-database-hosts
#  name: Get facts from database hosts (need IP)


# There are two OMERO and database servers. The production and analysis
# servers are handled separately since analysis should have a public
# password

# TODO: The set_fact tasks are duplicated from idr-omero.yml

- hosts: "{{ idr_environment | default('idr') }}-omero-hosts"
  pre_tasks:

  - name: Get database host
    set_fact:
      omero_db_host_ansible: "{{ hostvars[groups[idr_environment | default('idr') + '-database-hosts'][0]]['ansible_' + (idr_net_iface | default('eth0'))]['ipv4']['address']}}"

  - name: Generate random OMERO root password
    command: openssl rand -base64 15
    register: random_root_pass

  roles:
  - omero-user

  post_tasks:
  - name: Print OMERO root password
    debug:
      msg: "OMERO root password ({{ ansible_host }}): {{ random_root_pass.stdout }}"

  vars:
  - omero_user_admin_pass: "{{ random_root_pass.stdout }}"
  - omero_user_reset_root_password: "{{ random_root_pass.stdout }}"
  - omero_group_create:
    - name: demo
      type: read-only
  - omero_user_create:
    - login: public
      firstname: public
      lastname: user
      password: "{{ idr_secret_omero_web_public_password | default('public') }}"
      groups: "--group-name demo"
      force: True
  - omero_user_dbhost: "{{ omero_db_host_ansible }}"
  - omero_user_dbuser: "{{ omero_dbuser }}"
  - omero_user_dbname: "{{ omero_dbname }}"
  - omero_user_dbpassword: "{{ omero_dbpassword }}"


- hosts: "{{ idr_environment | default('idr') }}-a-omero-hosts"
  pre_tasks:

  - name: Get database host
    set_fact:
      omero_db_host_ansible: "{{ hostvars[groups[idr_environment | default('idr') + '-a-database-hosts'][0]]['ansible_' + (idr_net_iface | default('eth0'))]['ipv4']['address']}}"

  - name: Generate random OMERO root password
    command: openssl rand -base64 15
    register: random_root_pass

  roles:
  - omero-user

  post_tasks:

  - name: Print OMERO root password
    debug:
      msg: "OMERO root password ({{ ansible_host }}): {{ random_root_pass.stdout }}"

  - name: Save root ice.config
    become: yes
    template:
      src: files/idr-root-ice-config.j2
      dest: /root/idr-root-ice.config
      mode: 0400

  vars:
  - omero_user_admin_pass: "{{ random_root_pass.stdout }}"
  - omero_user_reset_root_password: "{{ random_root_pass.stdout }}"
  - omero_group_create:
    - name: demo
      type: read-only
  - omero_user_create:
    - login: public
      firstname: public
      lastname: user
      password: public
      groups: "--group-name demo"
      force: True
  - omero_user_dbhost: "{{ omero_db_host_ansible }}"
  - omero_user_dbuser: "{{ omero_dbuser }}"
  - omero_user_dbname: "{{ omero_dbname }}"
  - omero_user_dbpassword: "{{ omero_dbpassword }}"
