---
# Playbook for creating local user accounts on Openstack instances

# Variables should be in a private group_vars file
- hosts: >
    {{ idr_environment | default('idr') }}-hosts
    {{ idr_environment | default('idr') }}-a-hosts
    management-hosts
  roles:
  - role: sudoers
#    sudoers_individual_commands:
  - role: local-accounts
#    local_accounts_create:
