# Self-contained Ansible playbook for setting up the Embassy IDR NFS shares
- hosts: >
    {{ idr_environment | default('idr') }}-ebi-nfs
    {{ idr_environment | default('idr') }}-a-ebi-nfs

  roles:

  # The NFS network
  - role: network
    network_basic_ifaces:
    - device: eth1
      bootproto: dhcp
      mtu:
      type: Ethernet

  tasks:

  - name: Create NFS group
    become: yes
    group:
      gid: 1030
      name: idrnfs
      state: present

  - name: Create NFS user
    become: yes
    user:
      group: idrnfs
      name: idrnfs
      state: present
      uid: 6166

  - name: Mount NFS share
    become: yes
    mount:
      fstype: nfs
      name: "{{ nfs_mountpoint }}"
      opts: rsize=8192,wsize=8192,timeo=14,intr
      src: 10.35.106.250:/ivol_bioimage_sm
      state: mounted

  - name: Create filesets parent dir
    become: yes
    file:
      path: "{{ local_filesets_sym | dirname }}"
      state: directory

  - name: Create filesets symlink
    become: yes
    file:
      force: yes
      path: "{{ local_filesets_sym }}"
      src: "{{ nfs_filesets_dir }}"
      state: link


  vars:
    nfs_mountpoint: /nfs/bioimage
    nfs_filesets_dir: /nfs/bioimage/drop/complete
    local_filesets_sym: /uod/idr/filesets
