---
# defaults file for roles/jenkinsslave

jenkinsuser: hudson
jenkinsworkdir: /opt/hudson
authorized_key: "ssh-rsa KEY"
snoopy_dir_path: ""
gitconfig:
  user: email@example.org
  name: Firstname Lastname
  githubuser: example-user
  githubtoken: example-token

spacewalk: False