---
# Playbook for preparing IDR openstack nodes

# idr-initial.yml must have already been run

- hosts: idr-openstack

  roles:
  - role: network
  - role: logrotate

  vars:
    network_ifaces: "{{ post_network_ifaces }}"

  tasks:
    - name: add extra packages
      become: yes
      yum:
        name: jq
        state: present
