# External Ansible roles required by this repository

- name: analysis-tools
  src: openmicroscopy.analysis-tools
  version: 1.0.0

- name: basedeps
  src: openmicroscopy.basedeps
  version: 1.0.0

- name: cli-utils
  src: openmicroscopy.cli-utils
  version: 1.0.0

- name: docker
  src: openmicroscopy.docker
  version: 1.0.0

- name: docker-tools
  src: openmicroscopy.docker-tools
  version: 1.0.0

- name: haproxy
  src: openmicroscopy.haproxy
  version: 1.0.0

- name: ice
  src: openmicroscopy.ice
  version: 1.0.0

- name: java
  src: openmicroscopy.java
  version: 2.0.0

- name: jekyll-build
  src: openmicroscopy.jekyll-build
  version: 1.0.0

- name: local-accounts
  src: openmicroscopy.local-accounts
  version: 1.0.0

- name: logrotate
  src: openmicroscopy.logrotate
  version: 1.0.0

- name: lvm-partition
  src: openmicroscopy.lvm-partition
  version: 1.0.0

- name: munin
  src: openmicroscopy.munin
  version: 1.1.3-openmicroscopy1

- name: munin-node
  src: openmicroscopy.munin-node
  version: 1.2.1-openmicroscopy1

- name: network-cloud-interfaces
  src: openmicroscopy.network-cloud-interfaces
  version: 1.1.0

- name: nfs-mount
  src: openmicroscopy.nfs-mount
  version: 1.0.0

- name: nfs-share
  src: openmicroscopy.nfs-share
  version: 1.0.0

- name: nginx
  src: openmicroscopy.nginx
  version: 1.0.0

- name: nginx-proxy
  src: openmicroscopy.nginx-proxy
  version: 1.0.0

- name: nginx-ssl-selfsigned
  src: openmicroscopy.nginx-ssl-selfsigned
  version: 1.0.0

- name: omero-logmonitor
  src: openmicroscopy.omero-logmonitor
  version: 1.0.0

- name: omero-python-deps
  src: openmicroscopy.omero-python-deps
  version: 1.0.0

- name: omero-server
  src: openmicroscopy.omero-server
  version: 1.1.0

- name: omero-web-runtime
  src: openmicroscopy.omero-web-runtime
  version: 1.0.0

- name: openstack-volume-storage
  src: openmicroscopy.openstack-volume-storage
  version: 1.0.0

- name: postgresql
  src: openmicroscopy.postgresql
  version: 2.0.0

- name: python-pydata
  src: openmicroscopy.python-pydata
  version: 1.0.0

- name: redis
  src: openmicroscopy.redis
  version: 1.0.0

- name: samba-client
  src: openmicroscopy.samba-client
  version: 1.0.0

- name: selinux-utils
  src: openmicroscopy.selinux-utils
  version: 1.0.0

- name: storage-volume-initialise
  src: openmicroscopy.storage-volume-initialise
  version: 1.0.0

- name: sudoers
  src: openmicroscopy.sudoers
  version: 1.0.0

- name: upgrade-distpackages
  src: openmicroscopy.upgrade-distpackages
  version: 1.0.0

- name: versioncontrol-utils
  src: openmicroscopy.versioncontrol-utils
  version: 1.0.0
