---
- name: OME Website Setup
  hosts: web-linux # TODO?
  vars:
    ansible_user: centos

  roles:
    - role: versioncontrol-utils
    - role: jenkinsslave

- include: jekyll-playbooks/jekyll-install.yml
  tags: jekyll-install

- include: jekyll-playbooks/jekyll-deploy.yml
  tags: jekyll-deploy
