---
# tasks file for roles/nginx-proxy cache setup

# If caching is enabled for any proxies the nginx cache must be configured
- name: nginx | check cache configuration
  fail:
    msg: "Caching enabled for {{ item.location }} but nginx_proxy_caches is empty"
  when: (item.cache_validity | default(False)) and not nginx_proxy_caches
  with_items: "{{ nginx_proxy_backends }}"

- name: nginx | create cache directories
  become: yes
  file:
    dest: "{{ nginx_proxy_cache_parent_path }}/{{ item.name }}"
    group: nginx
    mode: 0750
    owner: nginx
    state: directory
  with_items: "{{ nginx_proxy_caches }}"
  when: nginx_proxy_caches

- name: nginx | proxy cache config
  become: yes
  template:
    src: nginx-confd-proxy-cache.j2
    dest: /etc/nginx/conf.d/proxy-cache.conf
  when: nginx_proxy_caches
  notify:
    - restart nginx

- name: nginx | proxy cache config
  become: yes
  file:
    dest: /etc/nginx/conf.d/proxy-cache.conf
    state: absent
  notify:
    - restart nginx
  when: not nginx_proxy_caches
